//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealDunia.Domain.DealDuniaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ItemRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchIndex {
            get {
                return this.SearchIndexField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchIndexField, value) != true)) {
                    this.SearchIndexField = value;
                    this.RaisePropertyChanged("SearchIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ResponseGroup {
            get {
                return this.ResponseGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseGroupField, value) != true)) {
                    this.ResponseGroupField = value;
                    this.RaisePropertyChanged("ResponseGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DealDuniaServiceReference.AmazonSoap")]
    public interface AmazonSoap {
        
        // CODEGEN: Generating message contract since element name requestParams from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemSearch", ReplyAction="*")]
        DealDunia.Domain.DealDuniaServiceReference.ItemSearchResponse ItemSearch(DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<DealDunia.Domain.DealDuniaServiceReference.ItemSearchResponse> ItemSearchAsync(DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ItemSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ItemSearch", Namespace="http://tempuri.org/", Order=0)]
        public DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequestBody Body;
        
        public ItemSearchRequest() {
        }
        
        public ItemSearchRequest(DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ItemSearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DealDunia.Domain.DealDuniaServiceReference.ItemRequest requestParams;
        
        public ItemSearchRequestBody() {
        }
        
        public ItemSearchRequestBody(DealDunia.Domain.DealDuniaServiceReference.ItemRequest requestParams) {
            this.requestParams = requestParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ItemSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ItemSearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public DealDunia.Domain.DealDuniaServiceReference.ItemSearchResponseBody Body;
        
        public ItemSearchResponse() {
        }
        
        public ItemSearchResponse(DealDunia.Domain.DealDuniaServiceReference.ItemSearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ItemSearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ItemSearchResult;
        
        public ItemSearchResponseBody() {
        }
        
        public ItemSearchResponseBody(System.Xml.Linq.XElement ItemSearchResult) {
            this.ItemSearchResult = ItemSearchResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AmazonSoapChannel : DealDunia.Domain.DealDuniaServiceReference.AmazonSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AmazonSoapClient : System.ServiceModel.ClientBase<DealDunia.Domain.DealDuniaServiceReference.AmazonSoap>, DealDunia.Domain.DealDuniaServiceReference.AmazonSoap {
        
        public AmazonSoapClient() {
        }
        
        public AmazonSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AmazonSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmazonSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmazonSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealDunia.Domain.DealDuniaServiceReference.ItemSearchResponse DealDunia.Domain.DealDuniaServiceReference.AmazonSoap.ItemSearch(DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequest request) {
            return base.Channel.ItemSearch(request);
        }
        
        public System.Xml.Linq.XElement ItemSearch(DealDunia.Domain.DealDuniaServiceReference.ItemRequest requestParams) {
            DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequest inValue = new DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequest();
            inValue.Body = new DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequestBody();
            inValue.Body.requestParams = requestParams;
            DealDunia.Domain.DealDuniaServiceReference.ItemSearchResponse retVal = ((DealDunia.Domain.DealDuniaServiceReference.AmazonSoap)(this)).ItemSearch(inValue);
            return retVal.Body.ItemSearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DealDunia.Domain.DealDuniaServiceReference.ItemSearchResponse> DealDunia.Domain.DealDuniaServiceReference.AmazonSoap.ItemSearchAsync(DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequest request) {
            return base.Channel.ItemSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<DealDunia.Domain.DealDuniaServiceReference.ItemSearchResponse> ItemSearchAsync(DealDunia.Domain.DealDuniaServiceReference.ItemRequest requestParams) {
            DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequest inValue = new DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequest();
            inValue.Body = new DealDunia.Domain.DealDuniaServiceReference.ItemSearchRequestBody();
            inValue.Body.requestParams = requestParams;
            return ((DealDunia.Domain.DealDuniaServiceReference.AmazonSoap)(this)).ItemSearchAsync(inValue);
        }
    }
}
