//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealDunia.Web.Areas
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreCategory
    {
        public short StoreCategoryId { get; set; }
        public string StoreCategoryName { get; set; }
        public string Image { get; set; }
        public Nullable<short> ParentId { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
