//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealDunia.Web.Areas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.ExcDeals = new HashSet<ExcDeal>();
        }
    
        public short StoreId { get; set; }
        public string StoreName { get; set; }
        public string StoreURL { get; set; }
        public string StoreImage { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public Nullable<bool> Affiliate { get; set; }
        public string AffiliateId { get; set; }
        public Nullable<short> StoreSourceId { get; set; }
        public Nullable<int> SourceStoreId { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<ExcDeal> ExcDeals { get; set; }
    }
}
