//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealDunia.Web.Areas
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreCategoryMap
    {
        public int StoreCatMapId { get; set; }
        public short StoreId { get; set; }
        public short StoreCategoryId { get; set; }
        public string URL { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual StoreCategory StoreCategory { get; set; }
        public virtual Store Store { get; set; }
    }
}
