//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealDunia.Web.Areas
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreSource
    {
        public StoreSource()
        {
            this.Coupons = new HashSet<Coupon>();
            this.Stores = new HashSet<Store>();
        }
    
        public short StoreSourceId { get; set; }
        public string StoreSourceCode { get; set; }
        public string StoreSourceName { get; set; }
    
        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual ICollection<Store> Stores { get; set; }
    }
}
